# config/config.yml
defaults: &defaults

  redis:
    host: 127.0.0.1
    port: 6379

  app_name: "Mac工作台"
  username_exclusion:
    - editor
    - editors
    - admin
    - administrator
    - cpanel
    - photo
    - photos
    - recents
    - account
    - accounts
    - user
    - users
    - '403'
    - '404'
    - '422'
    - '500'

  qiniu_access_key: 's1uJ3BWruFnHmlEEZK-vI8Kx2Fs_-akrbP8kPpd-'
  qiniu_secret_key: 'BAEX6qkmvBlvxKxENOPROXNHrzJgFRcObXwOhoyM'

  photo_bucket: 'macdesks'
  cdn_domain:   'http://macdesks.qiniudn.com'
  # cdn_domain:   'miclle.u.qiniudn.com'

  private_bucket: 'private-macdesks'
  private_cdn_domain:   'http://private-macdesks.qiniudn.com'
  # private_cdn_domain:   'http://miclle-private.qiniudn.com'

  static_bucket: 'miclle-static'
  static_cdn_domain: 'http://static.miclle.com'
  # static_cdn_domain: 'http://miclle-static.qiniudn.com'

  photo:
    versions:
      thumb:   'thumb'  # width: 50px,   height: 50px
      xsmall:  'xsmall' # width: 140px,  height: 140px
      small:   'small'  # width: 280px,  height: 280px
      medium:  'medium' # width: 440px,  height: 440px
      large:   'large'  # width: 600px,  height: 600px
      xlarge:  'xlarge' # width: 1200px, height: 1200px
      xxlarge: 'xxlarge'  # width: 1920px

  exception_recipients:
    - jun1st.feng@gmail.com

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults